title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/time-machine@v0.2.0
#theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-remote-theme


gems:
  jekyll-remote-theme:
    path: ../  # Adjust this path if your theme is located elsewhere
